extraction:
  python:
    after_prepare:
      - |
        # https://discuss.lgtm.com/t/determination-of-python-requirements/974/4
        sed -i 's/\("pyOpenSSL\)/\# Dependency removed for lgtm  (see .lgtm.yml): \1/g' src/allmydata/_auto_deps.py

queries:
  # This generates spurious errors for calls by interface because of the
  # zope.interface choice to exclude self from method signatures.  So, turn it
  # off.
  - exclude: "py/call/wrong-arguments"

  # The premise of this query is broken.  The errors it produces are nonsense.
  # There is no such thing as a "procedure" in Python and "None" is not
  # meaningless.
  - exclude: "py/procedure-return-value-used"

  # It is true that this query identifies things which are sometimes mistakes.
  # However, it also identifies things which are entirely valid.  Therefore,
  # it produces noisy results.
  - exclude: "py/implicit-string-concatenation-in-list"