[tool.towncrier]
    package_dir = "src"
    package = "magic_folder"
    filename = "NEWS.rst"
    directory = "newsfragments"
    start_string = ".. towncrier start line"
    title_format = "Release {version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/LeastAuthority/magic-folder/issues/{issue}>`_"
    underlines = [
        "'",
        "-",
        "~",
    ]

    # These are documented in development.rst.  Please update the docs if you
    # update this configuration.
    [[tool.towncrier.type]]
        directory = "incompat"
        name = "Backwards Incompatible Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug Fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "installation"
        name = "Dependency/Installation Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "configuration"
        name = "Configuration Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removed"
        name = "Removed Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "other"
        name = "Other Changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "minor"
        name = "Misc/Other"
        showcontent = false

[tool.black]
    target-version = ["py27"]
    extend-exclude = '''
    # A regex preceded with ^/ will apply only to files and directories
    # in the root of the project.
    /inotify.py
    |^/docs/conf.py
    '''
