name: Code Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codechecks:
    strategy:
      matrix:
        python-version:
          - "3.8"
    runs-on: ubuntu-20.04
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
      with:
        # Get enough history for the tags we get next to be meaningful.  0
        # means all history.
        fetch-depth: "0"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: codechecks
      run: tox -e codechecks
